import type { Metadata } from "next";
import { Josefin_Slab, Parkinsans, Josefin_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import WebsiteFooter from "@/components/layout/page-core/website-footer";

const josefinSlab = Josefin_Slab({
  variable: "--font-josefin-slab",
  display: "swap",
  subsets: ["latin"],
});

const parkinsans = Parkinsans({
  variable: "--font-parkinsans",
  display: "swap",
  subsets: ["latin"],
});

const josefinSans = Josefin_Sans({
  variable: "--font-josefin-sans",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${josefinSlab.variable} ${parkinsans.variable} ${josefinSans.variable}`} suppressHydrationWarning >
      <head />
      <body
        className="bg-background text-foreground antialiased"
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem 
          disableTransitionOnChange>
          {children}
          <WebsiteFooter />
        </ThemeProvider>
      </body>
    </html>
  );
}
